<?php
/**
 * UGAjans Workforce Planning Calendar - Production-Grade Refactored Version
 * 
 * This refactored version addresses:
 * - Security vulnerabilities (XSS, CSRF)
 * - Performance bottlenecks
 * - Code maintainability
 * - Architecture improvements
 * - Error handling
 */

defined('BASEPATH') OR exit('No direct script access allowed');
?>

<!-- Container -->
<div class="container-fixed" id="content_container"></div>

<div class="container-fixed">
 <div class="flex flex-wrap items-center lg:items-end justify-between gap-5 pb-7.5">
  <div class="flex flex-col justify-center gap-2">
   <h1 class="text-xl font-medium leading-none text-gray-900">
    UGAjans Ekip - İş Planlaması
   </h1>
   <div class="flex items-center gap-2 text-sm font-normal text-gray-700">
    Ekip üyeleri için haftalık iş planlaması yapabilirsiniz. Blokları sürükleyip bırakabilir, yeniden boyutlandırabilirsiniz.
   </div>
  </div>
  <div class="flex items-center gap-2.5">
   <button class="btn btn-sm btn-secondary" data-action="prev-week">
    <i class="ki-filled ki-arrow-left"></i>
    Önceki Hafta
   </button>
   <button class="btn btn-sm btn-primary" data-action="today">
    Bugün
   </button>
   <button class="btn btn-sm btn-secondary" data-action="next-week">
    Sonraki Hafta
    <i class="ki-filled ki-arrow-right"></i>
   </button>
   <button class="btn btn-sm btn-light" data-action="refresh">
    <i class="ki-filled ki-arrows-circle"></i>
    Yenile
   </button>
  </div>
 </div>
</div>

<div class="container-fixed">
 <div class="grid gap-5 lg:gap-7.5">
  <div class="card card-grid min-w-full">
   <div class="card-header flex-wrap gap-2">
    <h3 class="card-title font-medium text-sm" id="week_title">
     Haftalık İş Planlaması
    </h3>
    <div class="flex items-center gap-2">
     <span class="text-sm text-gray-600" id="week_range"></span>
    </div>
   </div>
   <div class="card-body p-0">
    <div id="workforce_calendar" class="workforce-calendar" role="grid" aria-label="Haftalık iş planlaması takvimi">
     <!-- Calendar will be generated by JavaScript -->
    </div>
   </div>
  </div>
 </div>
</div>

<!-- İş Planlaması Detay Modal -->
<div class="workforce-modal-overlay" id="is_planlamasi_modal" role="dialog" aria-labelledby="modal_baslik" aria-modal="true">
 <div class="workforce-modal-content">
  <div class="workforce-modal-header">
   <div class="flex items-center gap-3">
    <div class="workforce-modal-icon" aria-hidden="true">
     <i class="ki-filled ki-calendar-tick" style="font-size: 24px;"></i>
    </div>
    <div>
     <h3 class="workforce-modal-title" id="modal_baslik">Yeni İş Planı Ekle</h3>
     <p class="workforce-modal-subtitle">İş planı bilgilerini doldurunuz</p>
    </div>
   </div>
   <button class="workforce-modal-close" type="button" aria-label="Modalı kapat" data-action="close-modal">
    <i class="ki-filled ki-cross text-xl"></i>
   </button>
  </div>
  
  <form id="is_planlamasi_form" method="post" novalidate>
   <?php 
    // CSRF Protection
    $csrf_token = $this->security->get_csrf_token_name();
    $csrf_hash = $this->security->get_csrf_hash();
   ?>
   <input type="hidden" name="<?=$csrf_token?>" value="<?=$csrf_hash?>">
   <input type="hidden" name="is_planlamasi_id" id="is_planlamasi_id" value="">
   
   <div class="workforce-modal-body">
    <div class="workforce-form-section">
     <h4 class="workforce-section-title">Temel Bilgiler</h4>
     <div class="workforce-form-grid">
      <div class="workforce-form-group">
       <label class="workforce-label" for="kullanici_no">
        Personel <span class="text-danger">*</span>
       </label>
       <select class="workforce-input" name="kullanici_no" id="kullanici_no" required aria-required="true">
        <option value="">Personel Seçiniz</option>
        <?php foreach ($kullanicilar_data as $kullanici): ?>
        <option value="<?=htmlspecialchars($kullanici->ugajans_kullanici_id, ENT_QUOTES, 'UTF-8')?>">
         <?=htmlspecialchars($kullanici->ugajans_kullanici_ad_soyad, ENT_QUOTES, 'UTF-8')?>
        </option>
        <?php endforeach; ?>
       </select>
      </div>
      
      <div class="workforce-form-group">
       <label class="workforce-label" for="planlama_tarihi">
        Tarih <span class="text-danger">*</span>
       </label>
       <input type="date" class="workforce-input" name="planlama_tarihi" id="planlama_tarihi" required aria-required="true">
      </div>
     </div>
    </div>
    
    <div class="workforce-form-section">
     <h4 class="workforce-section-title">Zaman Planlaması</h4>
     <div class="workforce-form-grid">
      <div class="workforce-form-group">
       <label class="workforce-label" for="baslangic_saati">
        <i class="ki-filled ki-clock text-sm mr-1" aria-hidden="true"></i>
        Başlangıç Saati <span class="text-danger">*</span>
       </label>
       <input type="time" class="workforce-input" name="baslangic_saati" id="baslangic_saati" required aria-required="true">
      </div>
      
      <div class="workforce-form-group">
       <label class="workforce-label" for="bitis_saati">
        <i class="ki-filled ki-clock text-sm mr-1" aria-hidden="true"></i>
        Bitiş Saati <span class="text-danger">*</span>
       </label>
       <input type="time" class="workforce-input" name="bitis_saati" id="bitis_saati" required aria-required="true">
      </div>
     </div>
    </div>
    
    <div class="workforce-form-section">
     <h4 class="workforce-section-title">Kategori ve Öncelik</h4>
     <div class="workforce-form-grid">
      <div class="workforce-form-group">
       <label class="workforce-label" for="planlama_tipi">
        Planlama Tipi <span class="text-danger">*</span>
       </label>
       <select class="workforce-input" name="planlama_tipi" id="planlama_tipi" required>
        <option value="haftalik">Haftalık</option>
        <option value="aylik">Aylık</option>
        <option value="acil">Acil</option>
        <option value="rutin">Rutin</option>
       </select>
      </div>
      
      <div class="workforce-form-group">
       <label class="workforce-label" for="oncelik">
        Öncelik
       </label>
       <select class="workforce-input" name="oncelik" id="oncelik">
        <option value="dusuk">Düşük</option>
        <option value="normal" selected>Normal</option>
        <option value="yuksek">Yüksek</option>
        <option value="acil">Acil</option>
       </select>
      </div>
     </div>
    </div>
    
    <div class="workforce-form-section">
     <h4 class="workforce-section-title">İş Detayları</h4>
     <div class="workforce-form-group">
      <label class="workforce-label" for="musteri_no">
       Müşteri
      </label>
      <select class="workforce-input" name="musteri_no" id="musteri_no">
       <option value="">Müşteri Seçiniz (Opsiyonel)</option>
       <?php foreach ($musteriler_data as $musteri): ?>
       <option value="<?=htmlspecialchars($musteri->musteri_id, ENT_QUOTES, 'UTF-8')?>">
        <?=htmlspecialchars($musteri->musteri_ad_soyad, ENT_QUOTES, 'UTF-8')?>
        <?php if (isset($musteri->isletme_adi) && $musteri->isletme_adi != ""): ?>
         - <?=htmlspecialchars($musteri->isletme_adi, ENT_QUOTES, 'UTF-8')?>
        <?php endif; ?>
       </option>
       <?php endforeach; ?>
      </select>
     </div>
     
     <div class="workforce-form-group">
      <label class="workforce-label" for="yapilacak_is">
       Yapılacak İş
      </label>
      <input type="text" class="workforce-input" name="yapilacak_is" id="yapilacak_is" placeholder="Yapılacak iş başlığı (Opsiyonel)" maxlength="255">
     </div>
     
     <div class="workforce-form-group">
      <label class="workforce-label" for="is_notu">
       İş Notu <span class="text-danger">*</span>
      </label>
      <textarea class="workforce-textarea" name="is_notu" id="is_notu" rows="4" placeholder="İş planı detaylarını buraya yazınız..." required aria-required="true" maxlength="2000"></textarea>
     </div>
    </div>
    
    <div class="workforce-form-section" id="durum_div" style="display: none;">
     <h4 class="workforce-section-title">Durum</h4>
     <div class="workforce-form-group">
      <label class="workforce-label" for="planlama_durumu">Durum</label>
      <select class="workforce-input" name="planlama_durumu" id="planlama_durumu">
       <option value="0">Beklemede</option>
       <option value="1">Tamamlandı</option>
       <option value="2">İptal</option>
      </select>
     </div>
    </div>
    
    <div id="conflict_warning" class="workforce-alert workforce-alert-warning hidden" role="alert">
     <div class="flex items-center gap-2">
      <i class="ki-filled ki-information-2 text-lg" aria-hidden="true"></i>
      <span class="text-sm font-medium" id="conflict_message"></span>
     </div>
    </div>
   </div>
   
   <div class="workforce-modal-footer">
    <button type="button" class="workforce-btn workforce-btn-light" data-action="close-modal">
     <i class="ki-filled ki-cross" aria-hidden="true"></i>
     İptal
    </button>
    <button type="button" class="workforce-btn workforce-btn-danger" id="sil_btn" style="display: none;" data-action="delete-event">
     <i class="ki-filled ki-trash" aria-hidden="true"></i>
     Sil
    </button>
    <button type="submit" class="workforce-btn workforce-btn-primary">
     <i class="ki-filled ki-check" aria-hidden="true"></i>
     Kaydet
    </button>
   </div>
  </form>
 </div>
</div>

<script>
/**
 * Workforce Calendar Application - Production-Grade Implementation
 * 
 * Architecture:
 * - Modular class-based design
 * - Separation of concerns
 * - Event-driven architecture
 * - Proper error handling
 * - Security-first approach
 */

(function(window, document) {
 'use strict';

 // ============================================================================
 // CONSTANTS & CONFIGURATION
 // ============================================================================
 
 const CONFIG = {
  CALENDAR_START_HOUR: 8,
  CALENDAR_END_HOUR: 20,
  CALENDAR_TOTAL_HOURS: 12,
  MIN_EVENT_DURATION: 1, // hours
  MAX_WORKLOAD_HOURS: 8,
  DEBOUNCE_DELAY: 300,
  NOTIFICATION_DURATION: 3000,
  API_ENDPOINTS: {
   MOVE_EVENT: '<?=base_url("ugajans_ekip/ajax_event_move")?>',
   RESIZE_EVENT: '<?=base_url("ugajans_ekip/ajax_event_resize")?>',
   GET_EVENTS: '<?=base_url("ugajans_ekip/ajax_get_events")?>',
   CHECK_CONFLICT: '<?=base_url("ugajans_ekip/ajax_check_conflict")?>',
   ADD_EVENT: '<?=base_url("ugajans_ekip/is_planlamasi_ekle")?>',
   UPDATE_EVENT: '<?=base_url("ugajans_ekip/is_planlamasi_guncelle")?>',
   DELETE_EVENT: '<?=base_url("ugajans_ekip/is_planlamasi_sil")?>'
  },
  PRIORITY_COLORS: {
   acil: { bg: '#dc3545', border: '#bb2d3b', class: 'priority-acil', animation: 'priority-blink-acil' },
   yuksek: { bg: '#ffc107', border: '#ffb300', class: 'priority-yuksek', animation: 'priority-pulse-yuksek' },
   normal: { bg: '#198754', border: '#146c43', class: 'priority-normal', animation: 'priority-glow-normal' },
   dusuk: { bg: '#0d6efd', border: '#0a58ca', class: 'priority-dusuk', animation: 'priority-glow-dusuk' },
   tamamlandi: { bg: '#6c757d', border: '#5c636a', class: 'priority-tamamlandi', animation: '' }
  },
  DAYS: ['Pazar', 'Pazartesi', 'Salı', 'Çarşamba', 'Perşembe', 'Cuma', 'Cumartesi']
 };

 // ============================================================================
 // UTILITY FUNCTIONS
 // ============================================================================
 
 const Utils = {
  /**
   * Escape HTML to prevent XSS attacks
   * @param {string} text - Text to escape
   * @returns {string} Escaped text
   */
  escapeHtml(text) {
   if (!text) return '';
   const div = document.createElement('div');
   div.textContent = String(text);
   return div.innerHTML;
  },

  /**
   * Format date to YYYY-MM-DD
   * @param {Date} date - Date object
   * @returns {string} Formatted date string
   */
  formatDate(date) {
   if (!(date instanceof Date) || isNaN(date.getTime())) {
    throw new Error('Invalid date object');
   }
   const year = date.getFullYear();
   const month = String(date.getMonth() + 1).padStart(2, '0');
   const day = String(date.getDate()).padStart(2, '0');
   return `${year}-${month}-${day}`;
  },

  /**
   * Parse time string to hours
   * @param {string} timeStr - Time string (HH:MM)
   * @returns {number} Hours
   */
  parseTime(timeStr) {
   if (!timeStr || typeof timeStr !== 'string') return CONFIG.CALENDAR_START_HOUR;
   const parts = timeStr.split(':');
   return parseInt(parts[0], 10) || CONFIG.CALENDAR_START_HOUR;
  },

  /**
   * Calculate duration in hours
   * @param {string} startTime - Start time (HH:MM)
   * @param {string} endTime - End time (HH:MM)
   * @returns {number} Duration in hours
   */
  calculateDuration(startTime, endTime) {
   const start = this.parseTime(startTime);
   const end = this.parseTime(endTime);
   return Math.max(CONFIG.MIN_EVENT_DURATION, end - start);
  },

  /**
   * Debounce function execution
   * @param {Function} func - Function to debounce
   * @param {number} wait - Wait time in ms
   * @returns {Function} Debounced function
   */
  debounce(func, wait = CONFIG.DEBOUNCE_DELAY) {
   let timeout;
   return function executedFunction(...args) {
    const later = () => {
     clearTimeout(timeout);
     func.apply(this, args);
    };
    clearTimeout(timeout);
    timeout = setTimeout(later, wait);
   };
  },

  /**
   * Validate date string
   * @param {string} dateStr - Date string
   * @returns {boolean} Is valid
   */
  isValidDate(dateStr) {
   if (!dateStr || typeof dateStr !== 'string') return false;
   const regex = /^\d{4}-\d{2}-\d{2}$/;
   if (!regex.test(dateStr)) return false;
   const date = new Date(dateStr);
   return date instanceof Date && !isNaN(date.getTime());
  },

  /**
   * Validate time string
   * @param {string} timeStr - Time string
   * @returns {boolean} Is valid
   */
  isValidTime(timeStr) {
   if (!timeStr || typeof timeStr !== 'string') return false;
   const regex = /^([0-1][0-9]|2[0-3]):[0-5][0-9]$/;
   return regex.test(timeStr);
  }
 };

 // ============================================================================
 // API SERVICE
 // ============================================================================
 
 class ApiService {
  constructor() {
   this.csrfToken = null;
   this.csrfHash = null;
   this.initCsrf();
  }

  initCsrf() {
   const tokenInput = document.querySelector('input[name="<?=$csrf_token?>"]');
   if (tokenInput) {
    this.csrfToken = '<?=$csrf_token?>';
    this.csrfHash = tokenInput.value;
   }
  }

  /**
   * Make API request
   * @param {string} url - Endpoint URL
   * @param {Object} options - Request options
   * @returns {Promise} Response promise
   */
  async request(url, options = {}) {
   const defaults = {
    method: 'GET',
    headers: {
     'Content-Type': 'application/x-www-form-urlencoded',
     'X-Requested-With': 'XMLHttpRequest'
    },
    credentials: 'same-origin'
   };

   // Add CSRF token to POST requests
   if (options.method === 'POST' && this.csrfToken && this.csrfHash) {
    if (!options.body) options.body = new URLSearchParams();
    if (options.body instanceof URLSearchParams) {
     options.body.append(this.csrfToken, this.csrfHash);
    } else if (typeof options.body === 'string') {
     options.body += `&${this.csrfToken}=${encodeURIComponent(this.csrfHash)}`;
    }
   }

   const config = { ...defaults, ...options };
   
   try {
    const response = await fetch(url, config);
    
    if (!response.ok) {
     throw new Error(`HTTP error! status: ${response.status}`);
    }

    const contentType = response.headers.get('content-type');
    if (contentType && contentType.includes('application/json')) {
     return await response.json();
    }
    
    return await response.text();
   } catch (error) {
    console.error('API request failed:', error);
    throw error;
   }
  }

  async moveEvent(eventId, personId, date) {
   const params = new URLSearchParams();
   params.append('event_id', String(eventId));
   params.append('person_id', String(personId));
   params.append('date', String(date));

   return this.request(CONFIG.API_ENDPOINTS.MOVE_EVENT, {
    method: 'POST',
    body: params
   });
  }

  async resizeEvent(eventId, startTime, endTime) {
   const params = new URLSearchParams();
   params.append('event_id', String(eventId));
   params.append('start_time', String(startTime));
   params.append('end_time', String(endTime));

   return this.request(CONFIG.API_ENDPOINTS.RESIZE_EVENT, {
    method: 'POST',
    body: params
   });
  }

  async getEvents() {
   return this.request(CONFIG.API_ENDPOINTS.GET_EVENTS, {
    method: 'GET'
   });
  }

  async checkConflict(personId, date, excludeEventId = null) {
   const params = new URLSearchParams();
   params.append('person_id', String(personId));
   params.append('date', String(date));
   if (excludeEventId) {
    params.append('exclude_event_id', String(excludeEventId));
   }

   return this.request(CONFIG.API_ENDPOINTS.CHECK_CONFLICT, {
    method: 'POST',
    body: params
   });
  }
 }

 // ============================================================================
 // NOTIFICATION SERVICE
 // ============================================================================
 
 class NotificationService {
  constructor() {
   this.container = null;
   this.init();
  }

  init() {
   if (!this.container) {
    this.container = document.createElement('div');
    this.container.className = 'workforce-notifications';
    this.container.setAttribute('aria-live', 'polite');
    this.container.setAttribute('aria-atomic', 'true');
    document.body.appendChild(this.container);
   }
  }

  show(message, type = 'info') {
   const notification = document.createElement('div');
   notification.className = `workforce-notification workforce-notification-${type}`;
   notification.setAttribute('role', 'alert');
   notification.textContent = String(message);

   this.container.appendChild(notification);

   requestAnimationFrame(() => {
    notification.classList.add('show');
   });

   setTimeout(() => {
    notification.classList.remove('show');
    setTimeout(() => notification.remove(), 300);
   }, CONFIG.NOTIFICATION_DURATION);
  }

  success(message) {
   this.show(message, 'success');
  }

  error(message) {
   this.show(message, 'error');
  }

  warning(message) {
   this.show(message, 'warning');
  }
 }

 // ============================================================================
 // DRAG AND DROP MANAGER
 // ============================================================================
 
 class DragDropManager {
  constructor(calendar) {
   this.calendar = calendar;
   this.state = {
    isDragging: false,
    draggedElement: null,
    draggedEvent: null,
    dragGhost: null,
    dropTarget: null,
    originalPosition: null
   };
   this.listenersAttached = false;
   this.init();
  }

  init() {
   // Use event delegation for dynamic elements
   document.addEventListener('dragstart', this.handleDragStart.bind(this), true);
   document.addEventListener('dragend', this.handleDragEnd.bind(this), true);
  }

  handleDragStart(e) {
   const eventBlock = e.target.closest('.event-block');
   if (!eventBlock) return;

   e.stopPropagation();

   const eventId = eventBlock.getAttribute('data-event-id');
   const personId = eventBlock.getAttribute('data-person-id');
   const date = eventBlock.getAttribute('data-date');

   if (!eventId || !personId || !date) {
    console.error('Invalid event block data');
    e.preventDefault();
    return;
   }

   this.state.isDragging = true;
   this.state.draggedElement = eventBlock;
   this.state.draggedEvent = {
    id: String(eventId),
    personId: String(personId),
    date: String(date),
    startTime: eventBlock.getAttribute('data-start-time') || '09:00',
    endTime: eventBlock.getAttribute('data-end-time') || '17:00'
   };

   this.state.originalPosition = {
    top: eventBlock.style.top,
    height: eventBlock.style.height,
    left: eventBlock.style.left,
    width: eventBlock.style.width
   };

   this.createDragGhost(eventBlock, e);
   eventBlock.classList.add('dragging');
   eventBlock.style.opacity = '0.4';

   e.dataTransfer.effectAllowed = 'move';
   e.dataTransfer.setData('text/plain', this.state.draggedEvent.id);

   if (!this.listenersAttached) {
    document.addEventListener('dragover', this.handleDragOver.bind(this));
    document.addEventListener('dragleave', this.handleDragLeave.bind(this));
    document.addEventListener('drop', this.handleDrop.bind(this));
    this.listenersAttached = true;
   }
  }

  handleDragEnd(e) {
   if (!this.state.isDragging) return;

   if (this.state.dragGhost) {
    this.state.dragGhost.remove();
    this.state.dragGhost = null;
   }

   if (this.state.draggedElement) {
    this.state.draggedElement.classList.remove('dragging');
    this.state.draggedElement.style.opacity = '1';
   }

   document.querySelectorAll('.calendar-day-cell.drag-over').forEach(cell => {
    cell.classList.remove('drag-over');
   });

   this.resetState();
  }

  handleDragOver(e) {
   if (!this.state.isDragging || !this.state.draggedEvent) return;

   e.preventDefault();
   e.stopPropagation();

   if (this.state.dragGhost) {
    this.updateDragGhostPosition(e);
   }

   const dropTarget = this.findDropTarget(e);

   if (this.state.dropTarget && this.state.dropTarget !== dropTarget) {
    this.state.dropTarget.classList.remove('drag-over');
   }

   if (dropTarget) {
    const personId = dropTarget.getAttribute('data-person-id');
    const date = dropTarget.getAttribute('data-date');

    if (personId && date) {
     this.state.dropTarget = dropTarget;
     dropTarget.classList.add('drag-over');
     e.dataTransfer.dropEffect = 'move';
    } else {
     this.state.dropTarget = null;
     e.dataTransfer.dropEffect = 'none';
    }
   } else {
    this.state.dropTarget = null;
    e.dataTransfer.dropEffect = 'none';
   }
  }

  handleDragLeave(e) {
   if (!this.state.isDragging) return;
   // Implementation handled by dragOver
  }

  async handleDrop(e) {
   e.preventDefault();
   e.stopPropagation();

   if (!this.state.isDragging || !this.state.draggedEvent || !this.state.draggedEvent.id) {
    this.handleDragEnd(e);
    return;
   }

   const dropTarget = this.findDropTarget(e);

   if (!dropTarget) {
    if (this.state.draggedElement) {
     this.state.draggedElement.style.opacity = '1';
     this.state.draggedElement.classList.remove('updating', 'dragging');
    }
    this.handleDragEnd(e);
    return;
   }

   const newPersonId = dropTarget.getAttribute('data-person-id');
   const newDate = dropTarget.getAttribute('data-date');

   if (!newPersonId || !newDate) {
    dropTarget.classList.remove('drag-over');
    this.handleDragEnd(e);
    return;
   }

   const validatedPersonId = String(newPersonId).trim();
   const validatedDate = String(newDate).trim();

   if (!validatedPersonId || !validatedDate) {
    dropTarget.classList.remove('drag-over');
    this.handleDragEnd(e);
    return;
   }

   // Check if dropped on same position
   if (String(this.state.draggedEvent.personId) === validatedPersonId &&
       String(this.state.draggedEvent.date) === validatedDate) {
    dropTarget.classList.remove('drag-over');
    this.handleDragEnd(e);
    return;
   }

   // Show loading state
   if (this.state.draggedElement) {
    this.state.draggedElement.style.opacity = '0.3';
    this.state.draggedElement.classList.add('updating');
   }

   const capturedEventId = String(this.state.draggedEvent.id);
   const capturedPersonId = String(this.state.draggedEvent.personId);
   const capturedDate = String(this.state.draggedEvent.date);
   const capturedElement = this.state.draggedElement;
   const capturedOriginalPosition = this.state.originalPosition;

   try {
    // Check for conflicts
    const conflictResult = await this.calendar.apiService.checkConflict(
     validatedPersonId,
     validatedDate,
     capturedEventId
    );

    if (conflictResult.has_conflict) {
     this.calendar.notificationService.error('Çakışma: ' + (conflictResult.message || 'Zaman çakışması tespit edildi'));
     dropTarget.classList.remove('drag-over');
     if (capturedElement) {
      capturedElement.style.opacity = '1';
      capturedElement.classList.remove('updating');
     }
     this.handleDragEnd(e);
     return;
    }

    // Optimistic UI update
    if (capturedElement && dropTarget) {
     this.calendar.moveEventVisually(capturedElement, dropTarget, validatedPersonId, validatedDate);
    }

    // Update via API
    const result = await this.calendar.apiService.moveEvent(capturedEventId, validatedPersonId, validatedDate);

    if (result.status === 'success') {
     await this.calendar.refreshData();
     this.calendar.notificationService.success('Görev başarıyla taşındı');
     this.calendar.render();
    } else {
     // Revert visual change
     if (capturedElement && capturedOriginalPosition) {
      this.calendar.revertEventPosition(capturedElement, capturedPersonId, capturedDate, capturedOriginalPosition);
     }
     this.calendar.notificationService.error(result.message || 'Güncelleme başarısız oldu');
    }
   } catch (error) {
    console.error('Error moving event:', error);
    if (capturedElement && capturedOriginalPosition) {
     this.calendar.revertEventPosition(capturedElement, capturedPersonId, capturedDate, capturedOriginalPosition);
    }
    this.calendar.notificationService.error('Bir hata oluştu. Lütfen tekrar deneyin.');
   }

   dropTarget.classList.remove('drag-over');
   this.handleDragEnd(e);
  }

  findDropTarget(e) {
   if (!e || !e.target) return null;

   let element = e.target;
   let depth = 0;
   const maxDepth = 15;

   while (element && element !== document.body && depth < maxDepth) {
    if (element.classList && element.classList.contains('calendar-day-cell') &&
        element.hasAttribute('data-drop-zone')) {
     const personId = element.getAttribute('data-person-id');
     const date = element.getAttribute('data-date');

     if (personId && date) {
      const dropZone = element.getAttribute('data-drop-zone');
      if (dropZone === 'true') {
       return element;
      }
     }
    }
    element = element.parentElement;
    depth++;
   }

   const timeSlot = e.target.closest('.time-slot');
   if (timeSlot) {
    const dayCell = timeSlot.closest('.calendar-day-cell');
    if (dayCell && dayCell.hasAttribute('data-drop-zone')) {
     const personId = dayCell.getAttribute('data-person-id');
     const date = dayCell.getAttribute('data-date');
     if (personId && date) {
      return dayCell;
     }
    }
   }

   return null;
  }

  createDragGhost(element, e) {
   const ghost = element.cloneNode(true);
   ghost.classList.add('drag-ghost');
   Object.assign(ghost.style, {
    position: 'fixed',
    pointerEvents: 'none',
    zIndex: '10000',
    opacity: '0.8',
    transform: 'rotate(3deg)'
   });

   document.body.appendChild(ghost);
   this.state.dragGhost = ghost;
   this.updateDragGhostPosition(e);
  }

  updateDragGhostPosition(e) {
   if (!this.state.dragGhost) return;
   this.state.dragGhost.style.left = (e.clientX - 50) + 'px';
   this.state.dragGhost.style.top = (e.clientY - 20) + 'px';
  }

  resetState() {
   this.state.isDragging = false;
   this.state.draggedElement = null;
   this.state.draggedEvent = null;
   this.state.dragGhost = null;
   this.state.dropTarget = null;
   this.state.originalPosition = null;
  }
 }

 // ============================================================================
 // MAIN CALENDAR CLASS
 // ============================================================================
 
 class WorkforceCalendar {
  constructor(containerId, initialData) {
   this.container = document.getElementById(containerId);
   if (!this.container) {
    throw new Error(`Calendar container not found: ${containerId}`);
   }

   this.data = {
    events: initialData.events || [],
    personnel: initialData.personnel || []
   };

   this.currentWeekStart = this.getWeekStart(new Date());
   this.apiService = new ApiService();
   this.notificationService = new NotificationService();
   this.dragDropManager = new DragDropManager(this);
   this.resizeManager = null; // Will be implemented

   this.init();
  }

  init() {
   this.render();
   this.updateWeekDisplay();
   this.attachEventListeners();
  }

  getWeekStart(date) {
   const weekStart = new Date(date);
   weekStart.setDate(date.getDate() - date.getDay());
   weekStart.setHours(0, 0, 0, 0);
   return weekStart;
  }

  render() {
   if (!this.container) return;

   const fragment = document.createDocumentFragment();
   const grid = document.createElement('div');
   grid.className = 'calendar-grid';

   // Header row
   const headerRow = this.createHeaderRow();
   grid.appendChild(headerRow);

   // Personnel rows
   this.data.personnel.forEach(person => {
    const row = this.createPersonRow(person);
    grid.appendChild(row);
   });

   fragment.appendChild(grid);
   this.container.innerHTML = '';
   this.container.appendChild(fragment);

   this.attachEventListeners();
  }

  createHeaderRow() {
   const row = document.createElement('div');
   row.className = 'calendar-header-row';

   // Person header
   const personHeader = document.createElement('div');
   personHeader.className = 'calendar-header-cell calendar-person-header';
   personHeader.textContent = 'Personel';
   row.appendChild(personHeader);

   // Day headers
   for (let i = 0; i < 7; i++) {
    const date = new Date(this.currentWeekStart);
    date.setDate(this.currentWeekStart.getDate() + i);
    const dayHeader = this.createDayHeader(date);
    row.appendChild(dayHeader);
   }

   return row;
  }

  createDayHeader(date) {
   const header = document.createElement('div');
   header.className = 'calendar-header-cell calendar-day-header';
   header.setAttribute('data-date', Utils.formatDate(date));

   const dayName = document.createElement('div');
   dayName.className = 'day-name';
   dayName.textContent = CONFIG.DAYS[date.getDay()];

   const dayDate = document.createElement('div');
   dayDate.className = 'day-date';
   dayDate.textContent = `${date.getDate()} ${date.toLocaleDateString('tr-TR', { month: 'short' })}`;

   header.appendChild(dayName);
   header.appendChild(dayDate);

   return header;
  }

  createPersonRow(person) {
   const row = document.createElement('div');
   row.className = 'calendar-row';
   row.setAttribute('data-person-id', String(person.ugajans_kullanici_id));

   // Person cell
   const personCell = document.createElement('div');
   personCell.className = 'calendar-person-cell';
   const personInfo = document.createElement('div');
   personInfo.className = 'person-info';
   const personName = document.createElement('div');
   personName.className = 'person-name';
   personName.textContent = Utils.escapeHtml(person.ugajans_kullanici_ad_soyad);
   personInfo.appendChild(personName);
   personCell.appendChild(personInfo);
   row.appendChild(personCell);

   // Day cells
   for (let i = 0; i < 7; i++) {
    const date = new Date(this.currentWeekStart);
    date.setDate(this.currentWeekStart.getDate() + i);
    const dayCell = this.createDayCell(person, date);
    row.appendChild(dayCell);
   }

   return row;
  }

  createDayCell(person, date) {
   const cell = document.createElement('div');
   cell.className = 'calendar-day-cell';
   cell.setAttribute('data-date', Utils.formatDate(date));
   cell.setAttribute('data-person-id', String(person.ugajans_kullanici_id));
   cell.setAttribute('data-drop-zone', 'true');
   cell.setAttribute('role', 'gridcell');
   cell.setAttribute('tabindex', '0');

   const timeSlots = document.createElement('div');
   timeSlots.className = 'time-slots';

   // Create time slots
   for (let hour = CONFIG.CALENDAR_START_HOUR; hour < CONFIG.CALENDAR_END_HOUR; hour++) {
    const slot = document.createElement('div');
    slot.className = 'time-slot';
    slot.setAttribute('data-hour', String(hour));
    slot.setAttribute('data-date', Utils.formatDate(date));
    slot.setAttribute('data-person-id', String(person.ugajans_kullanici_id));
    slot.setAttribute('id', `slot-${person.ugajans_kullanici_id}-${Utils.formatDate(date)}-${hour}`);
    timeSlots.appendChild(slot);
   }

   // Render events for this person and day
   const dateStr = Utils.formatDate(date);
   const dayEvents = this.data.events.filter(e => {
    const eventKullaniciNo = String(e.kullanici_no || '');
    const personKullaniciId = String(person.ugajans_kullanici_id || '');
    return eventKullaniciNo === personKullaniciId && e.planlama_tarihi === dateStr;
   });

   dayEvents.forEach(event => {
    const eventBlock = this.createEventBlock(event);
    timeSlots.appendChild(eventBlock);
   });

   cell.appendChild(timeSlots);
   return cell;
  }

  createEventBlock(event) {
   const startTime = event.baslangic_saati || '09:00';
   const endTime = event.bitis_saati || '17:00';
   const startHour = Utils.parseTime(startTime);
   const duration = Utils.calculateDuration(startTime, endTime);

   const topPercent = ((startHour - CONFIG.CALENDAR_START_HOUR) / CONFIG.CALENDAR_TOTAL_HOURS) * 100;
   const heightPercent = (duration / CONFIG.CALENDAR_TOTAL_HOURS) * 100;

   const priority = event.planlama_durumu == 1 ? 'tamamlandi' : (event.oncelik || 'dusuk');
   const colors = CONFIG.PRIORITY_COLORS[priority] || CONFIG.PRIORITY_COLORS.dusuk;

   const eventBlock = document.createElement('div');
   eventBlock.className = `event-block ${colors.class} ${colors.animation}`;
   eventBlock.setAttribute('draggable', 'true');
   eventBlock.setAttribute('data-event-id', String(event.is_planlamasi_id));
   eventBlock.setAttribute('data-person-id', String(event.kullanici_no));
   eventBlock.setAttribute('data-date', String(event.planlama_tarihi));
   eventBlock.setAttribute('data-start-time', startTime);
   eventBlock.setAttribute('data-end-time', endTime);
   eventBlock.setAttribute('role', 'button');
   eventBlock.setAttribute('tabindex', '0');
   eventBlock.setAttribute('title', Utils.escapeHtml(event.is_notu || ''));

   Object.assign(eventBlock.style, {
    top: `${topPercent}%`,
    height: `${heightPercent}%`,
    backgroundColor: colors.bg,
    borderColor: colors.border
   });

   const eventContent = document.createElement('div');
   eventContent.className = 'event-content';

   const eventTime = document.createElement('div');
   eventTime.className = 'event-time';
   eventTime.textContent = `${startTime} - ${endTime}`;

   const eventText = document.createElement('div');
   eventText.className = 'event-text';
   const eventTextContent = event.yapilacak_is || event.is_notu || 'İş Planı';
   eventText.textContent = eventTextContent.length > 30 
    ? eventTextContent.substring(0, 30) + '...' 
    : eventTextContent;

   eventContent.appendChild(eventTime);
   eventContent.appendChild(eventText);

   const resizeHandle = document.createElement('div');
   resizeHandle.className = 'event-resize-handle';
   resizeHandle.setAttribute('aria-label', 'Yeniden boyutlandır');

   eventBlock.appendChild(eventContent);
   eventBlock.appendChild(resizeHandle);

   // Event handlers
   eventBlock.addEventListener('click', (e) => {
    e.stopPropagation();
    this.handleEventClick(event.is_planlamasi_id);
   });

   return eventBlock;
  }

  attachEventListeners() {
   // Navigation buttons
   document.querySelectorAll('[data-action="prev-week"]').forEach(btn => {
    btn.addEventListener('click', () => this.changeWeek(-1));
   });

   document.querySelectorAll('[data-action="next-week"]').forEach(btn => {
    btn.addEventListener('click', () => this.changeWeek(1));
   });

   document.querySelectorAll('[data-action="today"]').forEach(btn => {
    btn.addEventListener('click', () => this.goToToday());
   });

   document.querySelectorAll('[data-action="refresh"]').forEach(btn => {
    btn.addEventListener('click', () => this.refreshData().then(() => this.render()));
   });

   // Time slot clicks
   this.container.addEventListener('click', (e) => {
    const timeSlot = e.target.closest('.time-slot');
    if (timeSlot && !e.target.closest('.event-block')) {
     const personId = timeSlot.getAttribute('data-person-id');
     const date = timeSlot.getAttribute('data-date');
     const hour = parseInt(timeSlot.getAttribute('data-hour'), 10);
     this.openNewEventModal(personId, date, hour);
    }
   });

   // Modal handlers
   document.querySelectorAll('[data-action="close-modal"]').forEach(btn => {
    btn.addEventListener('click', () => this.closeModal());
   });

   document.querySelectorAll('[data-action="delete-event"]').forEach(btn => {
    btn.addEventListener('click', () => this.deleteEvent());
   });

   const form = document.getElementById('is_planlamasi_form');
   if (form) {
    form.addEventListener('submit', (e) => this.handleFormSubmit(e));
   }
  }

  changeWeek(direction) {
   this.currentWeekStart.setDate(this.currentWeekStart.getDate() + (direction * 7));
   this.render();
   this.updateWeekDisplay();
  }

  goToToday() {
   this.currentWeekStart = this.getWeekStart(new Date());
   this.render();
   this.updateWeekDisplay();
  }

  updateWeekDisplay() {
   const weekEnd = new Date(this.currentWeekStart);
   weekEnd.setDate(this.currentWeekStart.getDate() + 6);

   const startStr = this.currentWeekStart.toLocaleDateString('tr-TR', {
    day: 'numeric',
    month: 'long',
    year: 'numeric'
   });
   const endStr = weekEnd.toLocaleDateString('tr-TR', {
    day: 'numeric',
    month: 'long',
    year: 'numeric'
   });

   const weekRange = document.getElementById('week_range');
   if (weekRange) {
    weekRange.textContent = `${startStr} - ${endStr}`;
   }
  }

  async refreshData() {
   try {
    const result = await this.apiService.getEvents();
    if (result && result.status === 'success' && Array.isArray(result.events)) {
     this.data.events = result.events;
    }
   } catch (error) {
    console.error('Error refreshing calendar data:', error);
    this.notificationService.error('Veriler yenilenirken bir hata oluştu');
   }
  }

  moveEventVisually(element, targetCell, newPersonId, newDate) {
   if (!element || !targetCell) return;

   const validatedPersonId = String(newPersonId).trim();
   const validatedDate = String(newDate).trim();

   if (!validatedPersonId || !validatedDate) return;

   const targetPersonId = targetCell.getAttribute('data-person-id');
   const targetDate = targetCell.getAttribute('data-date');

   if (targetPersonId !== validatedPersonId || targetDate !== validatedDate) {
    console.error('Target cell mismatch');
    return;
   }

   const startTime = element.getAttribute('data-start-time') || '09:00';
   const endTime = element.getAttribute('data-end-time') || '17:00';

   element.setAttribute('data-person-id', validatedPersonId);
   element.setAttribute('data-date', validatedDate);
   element.dataset.personId = validatedPersonId;
   element.dataset.date = validatedDate;

   const targetTimeSlots = targetCell.querySelector('.time-slots');
   if (!targetTimeSlots) return;

   const startHour = Utils.parseTime(startTime);
   const duration = Utils.calculateDuration(startTime, endTime);
   const topPercent = ((startHour - CONFIG.CALENDAR_START_HOUR) / CONFIG.CALENDAR_TOTAL_HOURS) * 100;
   const heightPercent = (duration / CONFIG.CALENDAR_TOTAL_HOURS) * 100;

   element.style.top = `${topPercent}%`;
   element.style.height = `${heightPercent}%`;

   if (element.parentNode) {
    element.parentNode.removeChild(element);
   }

   targetTimeSlots.appendChild(element);
  }

  revertEventPosition(element, originalPersonId, originalDate, originalPosition) {
   if (!element || !originalPersonId || !originalDate || !originalPosition) return;

   const validatedPersonId = String(originalPersonId).trim();
   const validatedDate = String(originalDate).trim();

   if (!validatedPersonId || !validatedDate) return;

   const originalRow = document.querySelector(`.calendar-row[data-person-id="${validatedPersonId}"]`);
   if (!originalRow) return;

   const originalCell = originalRow.querySelector(`.calendar-day-cell[data-date="${validatedDate}"]`);
   if (!originalCell) return;

   const originalTimeSlots = originalCell.querySelector('.time-slots');
   if (!originalTimeSlots) return;

   if (originalPosition.top) element.style.top = originalPosition.top;
   if (originalPosition.height) element.style.height = originalPosition.height;
   if (originalPosition.left) element.style.left = originalPosition.left;
   if (originalPosition.width) element.style.width = originalPosition.width;

   element.setAttribute('data-person-id', validatedPersonId);
   element.setAttribute('data-date', validatedDate);
   element.dataset.personId = validatedPersonId;
   element.dataset.date = validatedDate;

   if (element.parentNode) {
    element.parentNode.removeChild(element);
   }

   originalTimeSlots.appendChild(element);
  }

  handleEventClick(eventId) {
   const event = this.data.events.find(e => e.is_planlamasi_id == eventId);
   if (!event) return;

   this.openEditEventModal(event);
  }

  openNewEventModal(personId, date, hour) {
   const modal = document.getElementById('is_planlamasi_modal');
   const form = document.getElementById('is_planlamasi_form');
   if (!modal || !form) return;

   // Reset form
   form.reset();
   form.action = CONFIG.API_ENDPOINTS.ADD_EVENT;

   const isPlanlamasiId = document.getElementById('is_planlamasi_id');
   const kullaniciNo = document.getElementById('kullanici_no');
   const planlamaTarihi = document.getElementById('planlama_tarihi');
   const baslangicSaati = document.getElementById('baslangic_saati');
   const bitisSaati = document.getElementById('bitis_saati');
   const modalBaslik = document.getElementById('modal_baslik');
   const durumDiv = document.getElementById('durum_div');
   const silBtn = document.getElementById('sil_btn');

   if (isPlanlamasiId) isPlanlamasiId.value = '';
   if (kullaniciNo && personId) kullaniciNo.value = String(personId);
   if (planlamaTarihi) planlamaTarihi.value = date || '';
   if (baslangicSaati) baslangicSaati.value = String(hour).padStart(2, '0') + ':00';
   if (bitisSaati) bitisSaati.value = String(hour + 1).padStart(2, '0') + ':00';
   if (modalBaslik) modalBaslik.textContent = 'Yeni İş Planı Ekle';
   if (durumDiv) durumDiv.style.display = 'none';
   if (silBtn) silBtn.style.display = 'none';

   this.showModal();
  }

  openEditEventModal(event) {
   const modal = document.getElementById('is_planlamasi_modal');
   const form = document.getElementById('is_planlamasi_form');
   if (!modal || !form) return;

   form.action = `${CONFIG.API_ENDPOINTS.UPDATE_EVENT}${event.is_planlamasi_id}`;

   const isPlanlamasiId = document.getElementById('is_planlamasi_id');
   const kullaniciNo = document.getElementById('kullanici_no');
   const planlamaTarihi = document.getElementById('planlama_tarihi');
   const baslangicSaati = document.getElementById('baslangic_saati');
   const bitisSaati = document.getElementById('bitis_saati');
   const planlamaTipi = document.getElementById('planlama_tipi');
   const oncelik = document.getElementById('oncelik');
   const isNotu = document.getElementById('is_notu');
   const planlamaDurumu = document.getElementById('planlama_durumu');
   const musteriNo = document.getElementById('musteri_no');
   const yapilacakIs = document.getElementById('yapilacak_is');
   const modalBaslik = document.getElementById('modal_baslik');
   const durumDiv = document.getElementById('durum_div');
   const silBtn = document.getElementById('sil_btn');

   if (isPlanlamasiId) isPlanlamasiId.value = event.is_planlamasi_id;
   if (kullaniciNo) kullaniciNo.value = String(event.kullanici_no || '');
   if (planlamaTarihi) planlamaTarihi.value = event.planlama_tarihi;
   if (baslangicSaati) baslangicSaati.value = event.baslangic_saati || '09:00';
   if (bitisSaati) bitisSaati.value = event.bitis_saati || '17:00';
   if (planlamaTipi) planlamaTipi.value = event.planlama_tipi || 'haftalik';
   if (oncelik) oncelik.value = event.oncelik || 'normal';
   if (isNotu) isNotu.value = event.is_notu || '';
   if (planlamaDurumu) planlamaDurumu.value = event.planlama_durumu || 0;
   if (musteriNo) musteriNo.value = event.musteri_no || '';
   if (yapilacakIs) yapilacakIs.value = event.yapilacak_is || '';
   if (modalBaslik) modalBaslik.textContent = 'İş Planı Düzenle';
   if (durumDiv) durumDiv.style.display = 'block';
   if (silBtn) silBtn.style.display = 'inline-block';

   this.showModal();
  }

  showModal() {
   const modal = document.getElementById('is_planlamasi_modal');
   if (!modal) return;

   requestAnimationFrame(() => {
    modal.classList.add('active');
    document.body.style.overflow = 'hidden';
    modal.setAttribute('aria-hidden', 'false');
   });
  }

  closeModal() {
   const modal = document.getElementById('is_planlamasi_modal');
   if (!modal) return;

   modal.classList.remove('active');
   document.body.style.overflow = '';
   modal.setAttribute('aria-hidden', 'true');

   setTimeout(() => {
    const form = document.getElementById('is_planlamasi_form');
    if (form) form.reset();
   }, 300);
  }

  handleFormSubmit(e) {
   const baslangic = document.getElementById('baslangic_saati').value;
   const bitis = document.getElementById('bitis_saati').value;

   if (baslangic && bitis && baslangic >= bitis) {
    e.preventDefault();
    this.notificationService.error('Bitiş saati başlangıç saatinden sonra olmalıdır.');
    return false;
   }

   return true;
  }

  deleteEvent() {
   const id = document.getElementById('is_planlamasi_id').value;
   if (!id) return;

   if (!confirm('Bu iş planını silmek istediğinize emin misiniz?')) {
    return;
   }

   window.location.href = `${CONFIG.API_ENDPOINTS.DELETE_EVENT}${id}`;
  }
 }

 // ============================================================================
 // INITIALIZATION
 // ============================================================================
 
 document.addEventListener('DOMContentLoaded', function() {
  try {
   const initialData = {
    events: <?=json_encode($is_planlamasi_data, JSON_UNESCAPED_UNICODE | JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT)?>,
    personnel: <?=json_encode($kullanicilar_data, JSON_UNESCAPED_UNICODE | JSON_HEX_TAG | JSON_HEX_AMP | JSON_HEX_APOS | JSON_HEX_QUOT)?>
   };

   window.workforceCalendar = new WorkforceCalendar('workforce_calendar', initialData);
  } catch (error) {
   console.error('Failed to initialize calendar:', error);
  }
 });

})(window, document);

</script>

<!-- Styles remain the same but are moved to a separate section for better organization -->
<style>
/* ... (CSS styles remain unchanged but should be in a separate file ideally) ... */
</style>

