<!-- Container -->
<div class="container-fixed" id="content_container">
</div>
<!-- End of Container -->

<!-- Container -->
<div class="container-fixed">
 <div class="flex flex-wrap items-center lg:items-end justify-between gap-5 pb-7.5">
  <div class="flex flex-col justify-center gap-2">
   <h1 class="text-xl font-medium leading-none text-gray-900">
    UGAjans Ekip - İş Planlaması
   </h1>
   <div class="flex items-center gap-2 text-sm font-normal text-gray-700">
    Ekip üyeleri için haftalık iş planlaması yapabilirsiniz. Blokları sürükleyip bırakabilir, yeniden boyutlandırabilirsiniz.
   </div>
  </div>
  <div class="flex items-center gap-2.5">
   <button class="btn btn-sm btn-secondary" onclick="changeWeek(-1)">
    <i class="ki-filled ki-arrow-left"></i>
    Önceki Hafta
   </button>
   <button class="btn btn-sm btn-primary" onclick="goToToday()">
    Bugün
   </button>
   <button class="btn btn-sm btn-secondary" onclick="changeWeek(1)">
    Sonraki Hafta
    <i class="ki-filled ki-arrow-right"></i>
   </button>
   <button class="btn btn-sm btn-light" onclick="window.location.reload();">
    <i class="ki-filled ki-arrows-circle"></i>
    Yenile
   </button>
  </div>
 </div>
</div>
<!-- End of Container -->

<!-- Container -->
<div class="container-fixed">
 <div class="grid gap-5 lg:gap-7.5">
  <div class="card card-grid min-w-full">
   <div class="card-header flex-wrap gap-2">
    <h3 class="card-title font-medium text-sm" id="week_title">
     Haftalık İş Planlaması
    </h3>
    <div class="flex items-center gap-2">
     <span class="text-sm text-gray-600" id="week_range"></span>
    </div>
   </div>
   <div class="card-body p-0">
    <div id="workforce_calendar" class="workforce-calendar">
     <!-- Calendar will be generated by JavaScript -->
    </div>
   </div>
  </div>
 </div>
</div>
<!-- End of Container -->

<!-- İş Planlaması Detay Modal -->
<div class="workforce-modal-overlay" id="is_planlamasi_modal" onclick="handleModalOverlayClick(event)">
 <div class="workforce-modal-content" onclick="event.stopPropagation()">
  <div class="workforce-modal-header">
   <div class="flex items-center gap-3">
    <div class="workforce-modal-icon">
     <i class="ki-filled ki-calendar-tick" style="font-size: 24px;"></i>
    </div>
    <div>
     <h3 class="workforce-modal-title" id="modal_baslik">Yeni İş Planı Ekle</h3>
     <p class="workforce-modal-subtitle">İş planı bilgilerini doldurunuz</p>
    </div>
   </div>
   <button class="workforce-modal-close" onclick="closeModal()" type="button">
    <i class="ki-filled ki-cross text-xl"></i>
   </button>
  </div>
  
  <form id="is_planlamasi_form" action="<?=base_url("ugajans_ekip/is_planlamasi_ekle")?>" method="post" onsubmit="return validateForm(event)">
   <input type="hidden" name="is_planlamasi_id" id="is_planlamasi_id" value="">
   
   <div class="workforce-modal-body">
    <div class="workforce-form-section">
     <h4 class="workforce-section-title">Temel Bilgiler</h4>
     <div class="workforce-form-grid">
      <div class="workforce-form-group">
       <label class="workforce-label">
        Personel <span class="text-danger">*</span>
       </label>
       <select class="workforce-input" name="kullanici_no" id="kullanici_no" required>
        <option value="">Personel Seçiniz</option>
        <?php foreach ($kullanicilar_data as $kullanici): ?>
        <option value="<?=$kullanici->ugajans_kullanici_id?>"><?=$kullanici->ugajans_kullanici_ad_soyad?></option>
        <?php endforeach; ?>
       </select>
      </div>
      
      <div class="workforce-form-group">
       <label class="workforce-label">
        Tarih <span class="text-danger">*</span>
       </label>
       <input type="date" class="workforce-input" name="planlama_tarihi" id="planlama_tarihi" required>
      </div>
     </div>
    </div>
    
    <div class="workforce-form-section">
     <h4 class="workforce-section-title">Zaman Planlaması</h4>
     <div class="workforce-form-grid">
      <div class="workforce-form-group">
       <label class="workforce-label">
        <i class="ki-filled ki-clock text-sm mr-1"></i>
        Başlangıç Saati <span class="text-danger">*</span>
       </label>
       <input type="time" class="workforce-input" name="baslangic_saati" id="baslangic_saati" required>
      </div>
      
      <div class="workforce-form-group">
       <label class="workforce-label">
        <i class="ki-filled ki-clock text-sm mr-1"></i>
        Bitiş Saati <span class="text-danger">*</span>
       </label>
       <input type="time" class="workforce-input" name="bitis_saati" id="bitis_saati" required>
      </div>
     </div>
    </div>
    
    <div class="workforce-form-section">
     <h4 class="workforce-section-title">Kategori ve Öncelik</h4>
     <div class="workforce-form-grid">
      <div class="workforce-form-group">
       <label class="workforce-label">
        Planlama Tipi <span class="text-danger">*</span>
       </label>
       <select class="workforce-input" name="planlama_tipi" id="planlama_tipi" required>
        <option value="haftalik">Haftalık</option>
        <option value="aylik">Aylık</option>
        <option value="acil">Acil</option>
        <option value="rutin">Rutin</option>
       </select>
      </div>
      
      <div class="workforce-form-group">
       <label class="workforce-label">
        Öncelik
       </label>
       <select class="workforce-input" name="oncelik" id="oncelik">
        <option value="dusuk">Düşük</option>
        <option value="normal" selected>Normal</option>
        <option value="yuksek">Yüksek</option>
        <option value="acil">Acil</option>
       </select>
      </div>
     </div>
    </div>
    
    <div class="workforce-form-section">
     <h4 class="workforce-section-title">İş Detayları</h4>
     <div class="workforce-form-group">
      <label class="workforce-label">
       Müşteri
      </label>
      <select class="workforce-input" name="musteri_no" id="musteri_no">
       <option value="">Müşteri Seçiniz (Opsiyonel)</option>
       <?php foreach ($musteriler_data as $musteri): ?>
       <option value="<?=$musteri->musteri_id?>"><?=$musteri->musteri_ad_soyad?> <?=isset($musteri->isletme_adi) && $musteri->isletme_adi != "" ? " - ".$musteri->isletme_adi : ""?></option>
       <?php endforeach; ?>
      </select>
     </div>
     
     <div class="workforce-form-group">
      <label class="workforce-label">
       Yapılacak İş
      </label>
      <input type="text" class="workforce-input" name="yapilacak_is" id="yapilacak_is" placeholder="Yapılacak iş başlığı (Opsiyonel)">
     </div>
     
     <div class="workforce-form-group">
      <label class="workforce-label">
       İş Notu <span class="text-danger">*</span>
      </label>
      <textarea class="workforce-textarea" name="is_notu" id="is_notu" rows="4" placeholder="İş planı detaylarını buraya yazınız..." required></textarea>
     </div>
    </div>
    
    <div class="workforce-form-section" id="durum_div" style="display: none;">
     <h4 class="workforce-section-title">Durum</h4>
     <div class="workforce-form-group">
      <label class="workforce-label">Durum</label>
      <select class="workforce-input" name="planlama_durumu" id="planlama_durumu">
       <option value="0">Beklemede</option>
       <option value="1">Tamamlandı</option>
       <option value="2">İptal</option>
      </select>
     </div>
    </div>
    
    <div id="conflict_warning" class="workforce-alert workforce-alert-warning hidden">
     <div class="flex items-center gap-2">
      <i class="ki-filled ki-information-2 text-lg"></i>
      <span class="text-sm font-medium" id="conflict_message"></span>
     </div>
    </div>
   </div>
   
   <div class="workforce-modal-footer">
    <button type="button" class="workforce-btn workforce-btn-light" onclick="closeModal()">
     <i class="ki-filled ki-cross"></i>
     İptal
    </button>
    <button type="button" class="workforce-btn workforce-btn-danger" id="sil_btn" style="display: none;" onclick="silIsPlanlamasi()">
     <i class="ki-filled ki-trash"></i>
     Sil
    </button>
    <button type="submit" class="workforce-btn workforce-btn-primary">
     <i class="ki-filled ki-check"></i>
     Kaydet
    </button>
   </div>
  </form>
 </div>
</div>

<script>
// Global variables
let calendarData = {
 events: <?=json_encode($is_planlamasi_data, JSON_UNESCAPED_UNICODE)?>,
 personnel: <?=json_encode($kullanicilar_data, JSON_UNESCAPED_UNICODE)?>
};

let currentWeekStart = new Date();
currentWeekStart.setDate(currentWeekStart.getDate() - currentWeekStart.getDay()); // Start of week (Sunday)
currentWeekStart.setHours(0, 0, 0, 0);

let draggedElement = null;
let draggedEvent = null;
let resizeHandle = null;
let isResizing = false;

// Initialize calendar
document.addEventListener('DOMContentLoaded', function() {
 initCalendar();
 updateWeekDisplay();
});

function initCalendar() {
 const calendar = document.getElementById('workforce_calendar');
 if (!calendar) return;
 
 // Create calendar structure
 let html = '<div class="calendar-grid">';
 
 // Header row with days
 html += '<div class="calendar-header-row">';
 html += '<div class="calendar-header-cell calendar-person-header">Personel</div>';
 
 const days = ['Pazar', 'Pazartesi', 'Salı', 'Çarşamba', 'Perşembe', 'Cuma', 'Cumartesi'];
 const dayAbbr = ['Pz', 'Pt', 'Sa', 'Ça', 'Pe', 'Cu', 'Ct'];
 
 for (let i = 0; i < 7; i++) {
  const date = new Date(currentWeekStart);
  date.setDate(currentWeekStart.getDate() + i);
  const dayName = days[date.getDay()];
  const dayNum = date.getDate();
  const monthName = date.toLocaleDateString('tr-TR', { month: 'short' });
  
  html += `<div class="calendar-header-cell calendar-day-header" data-date="${formatDate(date)}">
    <div class="day-name">${dayName}</div>
    <div class="day-date">${dayNum} ${monthName}</div>
   </div>`;
 }
 html += '</div>';
 
 // Personnel rows
 calendarData.personnel.forEach(person => {
  html += '<div class="calendar-row" data-person-id="' + person.ugajans_kullanici_id + '">';
  html += '<div class="calendar-person-cell">';
  html += '<div class="person-info">';
  html += '<div class="person-name">' + escapeHtml(person.ugajans_kullanici_ad_soyad) + '</div>';
  html += '</div>';
  html += '</div>';
  
  // Time slots for each day
  for (let i = 0; i < 7; i++) {
   const date = new Date(currentWeekStart);
   date.setDate(currentWeekStart.getDate() + i);
   const dateStr = formatDate(date);
   
   html += `<div class="calendar-day-cell" data-date="${dateStr}" data-person-id="${person.ugajans_kullanici_id}" 
     ondrop="handleDrop(event)" ondragover="handleDragOver(event)" onclick="handleCellClick(event)">
    <div class="time-slots">`;
   
   // Create hourly time slots (8 AM to 8 PM)
   for (let hour = 8; hour < 20; hour++) {
    const slotId = `slot-${person.ugajans_kullanici_id}-${dateStr}-${hour}`;
    html += `<div class="time-slot" data-hour="${hour}" data-date="${dateStr}" data-person-id="${person.ugajans_kullanici_id}" 
      id="${slotId}"></div>`;
   }
   
   // Render events for this person and day
   const dayEvents = calendarData.events.filter(e => 
    e.kullanici_no == person.ugajans_kullanici_id && 
    e.planlama_tarihi === dateStr
   );
   
   dayEvents.forEach(event => {
    html += renderEventBlock(event);
   });
   
   html += '</div></div>';
  }
  
  html += '</div>';
 });
 
 html += '</div>';
 calendar.innerHTML = html;
 
 // Attach event listeners
 attachEventListeners();
}

function renderEventBlock(event) {
 const startTime = event.baslangic_saati || '09:00';
 const endTime = event.bitis_saati || '17:00';
 const startHour = parseInt(startTime.split(':')[0]);
 const endHour = parseInt(endTime.split(':')[0]);
 const duration = endHour - startHour;
 
 // Color coding based on type and priority
 let bgColor = '#0d6efd'; // Default blue
 let borderColor = '#0a58ca';
 
 if (event.planlama_tipi === 'acil') {
  bgColor = '#dc3545';
  borderColor = '#bb2d3b';
 } else if (event.planlama_tipi === 'rutin') {
  bgColor = '#198754';
  borderColor = '#146c43';
 } else if (event.oncelik === 'yuksek') {
  bgColor = '#ffc107';
  borderColor = '#ffb300';
 }
 
 if (event.planlama_durumu == 1) {
  bgColor = '#6c757d';
  borderColor = '#5c636a';
 }
 
 const topPercent = ((startHour - 8) / 12) * 100;
 const heightPercent = (duration / 12) * 100;
 
 const eventText = event.yapilacak_is || event.is_notu || 'İş Planı';
 const shortText = eventText.length > 30 ? eventText.substring(0, 30) + '...' : eventText;
 
 return `
  <div class="event-block" 
   draggable="true"
   data-event-id="${event.is_planlamasi_id}"
   data-person-id="${event.kullanici_no}"
   data-date="${event.planlama_tarihi}"
   data-start-time="${startTime}"
   data-end-time="${endTime}"
   style="top: ${topPercent}%; height: ${heightPercent}%; background-color: ${bgColor}; border-color: ${borderColor};"
   ondragstart="handleEventDragStart(event)"
   ondragend="handleEventDragEnd(event)"
   onclick="handleEventClick(event, ${event.is_planlamasi_id})"
   title="${escapeHtml(event.is_notu || '')}">
   <div class="event-content">
    <div class="event-time">${startTime} - ${endTime}</div>
    <div class="event-text">${escapeHtml(shortText)}</div>
   </div>
   <div class="event-resize-handle" 
    onmousedown="handleResizeStart(event, ${event.is_planlamasi_id})"></div>
  </div>
 `;
}

function attachEventListeners() {
 // Make time slots clickable for creating new events
 document.querySelectorAll('.time-slot').forEach(slot => {
  slot.addEventListener('click', function(e) {
   if (e.target.classList.contains('event-block') || e.target.closest('.event-block')) {
    return;
   }
   const personId = this.dataset.personId;
   const date = this.dataset.date;
   const hour = parseInt(this.dataset.hour);
   openNewEventModal(personId, date, hour);
  });
 });
}

function handleCellClick(e) {
 if (e.target.classList.contains('event-block') || e.target.closest('.event-block')) {
  return;
 }
 if (e.target.classList.contains('time-slot')) {
  const slot = e.target;
  const personId = slot.dataset.personId;
  const date = slot.dataset.date;
  const hour = parseInt(slot.dataset.hour);
  openNewEventModal(personId, date, hour);
 }
}

function openNewEventModal(personId, date, hour) {
 const modal = document.getElementById('is_planlamasi_modal');
 const form = document.getElementById('is_planlamasi_form');
 const modalBaslik = document.getElementById('modal_baslik');
 const isPlanlamasiId = document.getElementById('is_planlamasi_id');
 const kullaniciNo = document.getElementById('kullanici_no');
 const planlamaTarihi = document.getElementById('planlama_tarihi');
 const baslangicSaati = document.getElementById('baslangic_saati');
 const bitisSaati = document.getElementById('bitis_saati');
 const durumDiv = document.getElementById('durum_div');
 const silBtn = document.getElementById('sil_btn');
 const conflictWarning = document.getElementById('conflict_warning');
 
 if (!modal || !form) {
  console.error('Modal veya form elementi bulunamadı');
  return;
 }
 
 // Reset form
 if (isPlanlamasiId) isPlanlamasiId.value = '';
 if (kullaniciNo) kullaniciNo.value = personId || '';
 if (planlamaTarihi) planlamaTarihi.value = date || '';
 if (baslangicSaati) baslangicSaati.value = String(hour).padStart(2, '0') + ':00';
 if (bitisSaati) bitisSaati.value = String(hour + 1).padStart(2, '0') + ':00';
 if (modalBaslik) modalBaslik.textContent = 'Yeni İş Planı Ekle';
 if (form) form.action = '<?=base_url("ugajans_ekip/is_planlamasi_ekle")?>';
 if (durumDiv) durumDiv.style.display = 'none';
 if (silBtn) silBtn.style.display = 'none';
 if (conflictWarning) conflictWarning.classList.add('hidden');
 
 // Clear other fields
 const musteriNoEl = document.getElementById('musteri_no');
 const yapilacakIsEl = document.getElementById('yapilacak_is');
 const isNotuEl = document.getElementById('is_notu');
 const planlamaTipiEl = document.getElementById('planlama_tipi');
 const oncelikEl = document.getElementById('oncelik');
 
 if (musteriNoEl) musteriNoEl.value = '';
 if (yapilacakIsEl) yapilacakIsEl.value = '';
 if (isNotuEl) isNotuEl.value = '';
 if (planlamaTipiEl) planlamaTipiEl.value = 'haftalik';
 if (oncelikEl) oncelikEl.value = 'normal';
 
 // Open modal with animation
 requestAnimationFrame(function() {
  modal.classList.add('active');
  document.body.style.overflow = 'hidden';
 });
}

function handleEventClick(e, eventId) {
 e.stopPropagation();
 const event = calendarData.events.find(e => e.is_planlamasi_id == eventId);
 if (!event) return;
 
 const modal = document.getElementById('is_planlamasi_modal');
 const form = document.getElementById('is_planlamasi_form');
 const modalBaslik = document.getElementById('modal_baslik');
 const isPlanlamasiId = document.getElementById('is_planlamasi_id');
 const kullaniciNo = document.getElementById('kullanici_no');
 const planlamaTarihi = document.getElementById('planlama_tarihi');
 const baslangicSaati = document.getElementById('baslangic_saati');
 const bitisSaati = document.getElementById('bitis_saati');
 const planlamaTipi = document.getElementById('planlama_tipi');
 const oncelik = document.getElementById('oncelik');
 const isNotu = document.getElementById('is_notu');
 const planlamaDurumu = document.getElementById('planlama_durumu');
 const musteriNo = document.getElementById('musteri_no');
 const yapilacakIs = document.getElementById('yapilacak_is');
 const durumDiv = document.getElementById('durum_div');
 const silBtn = document.getElementById('sil_btn');
 const conflictWarning = document.getElementById('conflict_warning');
 
 if (!modal || !form) return;
 
 // Fill form with event data
 if (isPlanlamasiId) isPlanlamasiId.value = event.is_planlamasi_id;
 if (kullaniciNo) kullaniciNo.value = event.kullanici_no;
 if (planlamaTarihi) planlamaTarihi.value = event.planlama_tarihi;
 if (baslangicSaati) baslangicSaati.value = event.baslangic_saati || '09:00';
 if (bitisSaati) bitisSaati.value = event.bitis_saati || '17:00';
 if (planlamaTipi) planlamaTipi.value = event.planlama_tipi || 'haftalik';
 if (oncelik) oncelik.value = event.oncelik || 'normal';
 if (isNotu) isNotu.value = event.is_notu || '';
 if (planlamaDurumu) planlamaDurumu.value = event.planlama_durumu || 0;
 if (musteriNo) musteriNo.value = event.musteri_no || '';
 if (yapilacakIs) yapilacakIs.value = event.yapilacak_is || '';
 if (modalBaslik) modalBaslik.textContent = 'İş Planı Düzenle';
 if (form) form.action = '<?=base_url("ugajans_ekip/is_planlamasi_guncelle/")?>' + event.is_planlamasi_id;
 if (durumDiv) durumDiv.style.display = 'block';
 if (silBtn) silBtn.style.display = 'inline-block';
 if (conflictWarning) conflictWarning.classList.add('hidden');
 
 // Open modal with animation
 if (modal) {
  requestAnimationFrame(function() {
   modal.classList.add('active');
   document.body.style.overflow = 'hidden';
  });
 }
}

// Drag and Drop Functions
function handleEventDragStart(e) {
 draggedElement = e.target;
 draggedEvent = {
  id: e.target.dataset.eventId,
  personId: e.target.dataset.personId,
  date: e.target.dataset.date
 };
 e.target.style.opacity = '0.5';
 e.dataTransfer.effectAllowed = 'move';
}

function handleEventDragEnd(e) {
 if (draggedElement) {
  draggedElement.style.opacity = '1';
 }
 draggedElement = null;
 draggedEvent = null;
}

function handleDragOver(e) {
 e.preventDefault();
 e.dataTransfer.dropEffect = 'move';
 
 const cell = e.target.closest('.calendar-day-cell');
 if (cell && draggedEvent) {
  cell.classList.add('drag-over');
 }
}

function handleDrop(e) {
 e.preventDefault();
 const cell = e.target.closest('.calendar-day-cell');
 if (!cell || !draggedEvent) return;
 
 const newPersonId = cell.dataset.personId;
 const newDate = cell.dataset.date;
 
 if (draggedEvent.personId == newPersonId && draggedEvent.date === newDate) {
  cell.classList.remove('drag-over');
  return;
 }
 
 // Check for conflicts
 checkConflict(newPersonId, newDate, draggedEvent.id, function(hasConflict, message) {
  if (hasConflict) {
   alert('Çakışma: ' + message);
   cell.classList.remove('drag-over');
   return;
  }
  
  // Update event via AJAX
  updateEventPosition(draggedEvent.id, newPersonId, newDate, function(success) {
   if (success) {
    // Reload calendar
    location.reload();
   } else {
    alert('Güncelleme başarısız oldu.');
   }
   cell.classList.remove('drag-over');
  });
 });
}

// Resize Functions
function handleResizeStart(e, eventId) {
 e.stopPropagation();
 isResizing = true;
 resizeHandle = e.target;
 draggedEvent = {
  id: eventId
 };
 
 document.addEventListener('mousemove', handleResizeMove);
 document.addEventListener('mouseup', handleResizeEnd);
}

function handleResizeMove(e) {
 if (!isResizing || !resizeHandle) return;
 
 const eventBlock = resizeHandle.closest('.event-block');
 if (!eventBlock) return;
 
 const cell = eventBlock.closest('.calendar-day-cell');
 if (!cell) return;
 
 const rect = cell.getBoundingClientRect();
 const y = e.clientY - rect.top;
 const heightPercent = (y / rect.height) * 100;
 
 if (heightPercent > 5 && heightPercent < 95) {
  eventBlock.style.height = heightPercent + '%';
 }
}

function handleResizeEnd(e) {
 if (!isResizing || !resizeHandle || !draggedEvent) return;
 
 const eventBlock = resizeHandle.closest('.event-block');
 if (!eventBlock) return;
 
 const cell = eventBlock.closest('.calendar-day-cell');
 if (!cell) return;
 
 const rect = cell.getBoundingClientRect();
 const eventRect = eventBlock.getBoundingClientRect();
 const topPercent = ((eventRect.top - rect.top) / rect.height) * 100;
 const heightPercent = (eventRect.height / rect.height) * 100;
 
 // Calculate new start and end times
 const startHour = Math.round(8 + (topPercent / 100) * 12);
 const endHour = Math.round(startHour + (heightPercent / 100) * 12);
 
 const newStartTime = String(startHour).padStart(2, '0') + ':00';
 const newEndTime = String(endHour).padStart(2, '0') + ':00';
 
 // Update via AJAX
 updateEventTime(draggedEvent.id, newStartTime, newEndTime, function(success) {
  if (success) {
   location.reload();
  } else {
   alert('Güncelleme başarısız oldu.');
  }
 });
 
 isResizing = false;
 resizeHandle = null;
 draggedEvent = null;
 document.removeEventListener('mousemove', handleResizeMove);
 document.removeEventListener('mouseup', handleResizeEnd);
}

// AJAX Functions
function updateEventPosition(eventId, newPersonId, newDate, callback) {
 fetch('<?=base_url("ugajans_ekip/ajax_event_move")?>', {
  method: 'POST',
  headers: {
   'Content-Type': 'application/x-www-form-urlencoded',
   'X-Requested-With': 'XMLHttpRequest'
  },
  body: 'event_id=' + eventId + '&person_id=' + newPersonId + '&date=' + newDate
 })
 .then(response => response.json())
 .then(data => {
  if (data.status === 'success') {
   callback(true);
  } else {
   callback(false);
  }
 })
 .catch(error => {
  console.error('Error:', error);
  callback(false);
 });
}

function updateEventTime(eventId, startTime, endTime, callback) {
 fetch('<?=base_url("ugajans_ekip/ajax_event_resize")?>', {
  method: 'POST',
  headers: {
   'Content-Type': 'application/x-www-form-urlencoded',
   'X-Requested-With': 'XMLHttpRequest'
  },
  body: 'event_id=' + eventId + '&start_time=' + startTime + '&end_time=' + endTime
 })
 .then(response => response.json())
 .then(data => {
  if (data.status === 'success') {
   callback(true);
  } else {
   callback(false);
  }
 })
 .catch(error => {
  console.error('Error:', error);
  callback(false);
 });
}

function checkConflict(personId, date, excludeEventId, callback) {
 fetch('<?=base_url("ugajans_ekip/ajax_check_conflict")?>', {
  method: 'POST',
  headers: {
   'Content-Type': 'application/x-www-form-urlencoded',
   'X-Requested-With': 'XMLHttpRequest'
  },
  body: 'person_id=' + personId + '&date=' + date + '&exclude_event_id=' + (excludeEventId || '')
 })
 .then(response => response.json())
 .then(data => {
  callback(data.has_conflict, data.message || '');
 })
 .catch(error => {
  console.error('Error:', error);
  callback(false, '');
 });
}

// Week Navigation
function changeWeek(direction) {
 currentWeekStart.setDate(currentWeekStart.getDate() + (direction * 7));
 initCalendar();
 updateWeekDisplay();
}

function goToToday() {
 currentWeekStart = new Date();
 currentWeekStart.setDate(currentWeekStart.getDate() - currentWeekStart.getDay());
 currentWeekStart.setHours(0, 0, 0, 0);
 initCalendar();
 updateWeekDisplay();
}

function updateWeekDisplay() {
 const weekEnd = new Date(currentWeekStart);
 weekEnd.setDate(currentWeekStart.getDate() + 6);
 
 const startStr = currentWeekStart.toLocaleDateString('tr-TR', { day: 'numeric', month: 'long', year: 'numeric' });
 const endStr = weekEnd.toLocaleDateString('tr-TR', { day: 'numeric', month: 'long', year: 'numeric' });
 
 const weekRange = document.getElementById('week_range');
 if (weekRange) {
  weekRange.textContent = startStr + ' - ' + endStr;
 }
}

// Utility Functions
function formatDate(date) {
 const year = date.getFullYear();
 const month = String(date.getMonth() + 1).padStart(2, '0');
 const day = String(date.getDate()).padStart(2, '0');
 return year + '-' + month + '-' + day;
}

function escapeHtml(text) {
 if (!text) return '';
 const div = document.createElement('div');
 div.textContent = text;
 return div.innerHTML;
}

function closeModal() {
 const modal = document.getElementById('is_planlamasi_modal');
 if (modal) {
  modal.classList.remove('active');
  document.body.style.overflow = '';
  // Reset form after animation
  setTimeout(function() {
   const form = document.getElementById('is_planlamasi_form');
   if (form) {
    form.reset();
   }
  }, 300);
 }
}

function handleModalOverlayClick(e) {
 if (e.target.id === 'is_planlamasi_modal') {
  closeModal();
 }
}

function validateForm(e) {
 const baslangic = document.getElementById('baslangic_saati').value;
 const bitis = document.getElementById('bitis_saati').value;
 
 if (baslangic && bitis && baslangic >= bitis) {
  e.preventDefault();
  alert('Bitiş saati başlangıç saatinden sonra olmalıdır.');
  return false;
 }
 
 return true;
}

function silIsPlanlamasi() {
 const id = document.getElementById('is_planlamasi_id').value;
 if (id && confirm('Bu iş planını silmek istediğinize emin misiniz?')) {
  window.location.href = '<?=base_url("ugajans_ekip/is_planlamasi_sil/")?>' + id;
 }
}
</script>

<style>
.workforce-calendar {
 width: 100%;
 overflow-x: auto;
 background: white;
}

.calendar-grid {
 display: grid;
 grid-template-columns: 200px repeat(7, 1fr);
 min-width: 1400px;
}

.calendar-header-row {
 display: contents;
}

.calendar-header-cell {
 padding: 12px;
 background: #f8f9fa;
 border-bottom: 2px solid #dee2e6;
 font-weight: 600;
 text-align: center;
 position: sticky;
 top: 0;
 z-index: 10;
}

.calendar-person-header {
 background: #e9ecef;
}

.calendar-day-header {
 display: flex;
 flex-direction: column;
 gap: 4px;
}

.day-name {
 font-size: 14px;
 color: #495057;
}

.day-date {
 font-size: 16px;
 color: #212529;
}

.calendar-row {
 display: contents;
}

.calendar-person-cell {
 padding: 12px;
 background: #f8f9fa;
 border-right: 1px solid #dee2e6;
 border-bottom: 1px solid #dee2e6;
 position: sticky;
 left: 0;
 z-index: 5;
 background: #f8f9fa;
}

.person-info {
 display: flex;
 flex-direction: column;
 gap: 4px;
}

.person-name {
 font-weight: 600;
 color: #212529;
 font-size: 14px;
}

.calendar-day-cell {
 position: relative;
 min-height: 600px;
 border-right: 1px solid #dee2e6;
 border-bottom: 1px solid #dee2e6;
 background: white;
 cursor: pointer;
}

.calendar-day-cell:hover {
 background: #f8f9fa;
}

.calendar-day-cell.drag-over {
 background: #e7f3ff;
 border: 2px dashed #0d6efd;
}

.time-slots {
 position: relative;
 height: 100%;
 width: 100%;
}

.time-slot {
 height: calc(100% / 12);
 border-bottom: 1px solid #f0f0f0;
 position: relative;
}

.time-slot:hover {
 background: #f8f9fa;
}

.event-block {
 position: absolute;
 left: 2px;
 right: 2px;
 background: #0d6efd;
 border: 2px solid #0a58ca;
 border-radius: 4px;
 cursor: move;
 z-index: 20;
 overflow: hidden;
 box-shadow: 0 2px 4px rgba(0,0,0,0.1);
 transition: box-shadow 0.2s;
}

.event-block:hover {
 box-shadow: 0 4px 8px rgba(0,0,0,0.2);
 z-index: 21;
}

.event-block.dragging {
 opacity: 0.5;
}

.event-content {
 padding: 4px 8px;
 color: white;
 height: 100%;
 display: flex;
 flex-direction: column;
 justify-content: space-between;
}

.event-time {
 font-size: 11px;
 font-weight: 600;
 opacity: 0.9;
}

.event-text {
 font-size: 12px;
 font-weight: 500;
 line-height: 1.3;
 flex: 1;
 display: flex;
 align-items: center;
}

.event-resize-handle {
 position: absolute;
 bottom: 0;
 left: 0;
 right: 0;
 height: 6px;
 cursor: ns-resize;
 background: rgba(255,255,255,0.3);
}

.event-resize-handle:hover {
 background: rgba(255,255,255,0.5);
}

@media (max-width: 1200px) {
 .calendar-grid {
  min-width: 1000px;
 }
 
 .calendar-person-cell {
  min-width: 150px;
 }
}

/* Workforce Modal Styles */
.workforce-modal-overlay {
 position: fixed;
 top: 0;
 left: 0;
 right: 0;
 bottom: 0;
 background: rgba(0, 0, 0, 0.5);
 backdrop-filter: blur(4px);
 z-index: 9999;
 display: none;
 align-items: center;
 justify-content: center;
 padding: 20px;
 opacity: 0;
 visibility: hidden;
 transition: opacity 0.3s ease, visibility 0.3s ease;
 overflow-y: auto;
}

.workforce-modal-overlay.active {
 display: flex;
 opacity: 1;
 visibility: visible;
}

.workforce-modal-content {
 background: white;
 border-radius: 12px;
 box-shadow: 0 20px 60px rgba(0, 0, 0, 0.3);
 max-width: 900px;
 width: 100%;
 max-height: calc(90vh - 40px);
 margin: auto;
 display: flex;
 flex-direction: column;
 transform: scale(0.9) translateY(-20px);
 transition: transform 0.3s ease, opacity 0.3s ease;
 overflow: hidden;
 opacity: 0;
 position: relative;
}

.workforce-modal-overlay.active .workforce-modal-content {
 transform: scale(1) translateY(0);
 opacity: 1;
}

.workforce-modal-header {
 display: flex;
 align-items: center;
 justify-content: space-between;
 padding: 24px 28px;
 border-bottom: 1px solid #e5e7eb;
 background: linear-gradient(135deg, #f8f9fa 0%, #ffffff 100%);
}

.workforce-modal-icon {
 width: 48px;
 height: 48px;
 border-radius: 12px;
 background: linear-gradient(135deg, #0d6efd 0%, #0a58ca 100%);
 display: flex;
 align-items: center;
 justify-content: center;
 color: white;
 flex-shrink: 0;
}

.workforce-modal-title {
 font-size: 20px;
 font-weight: 700;
 color: #1f2937;
 margin: 0;
 line-height: 1.2;
}

.workforce-modal-subtitle {
 font-size: 13px;
 color: #6b7280;
 margin: 4px 0 0 0;
}

.workforce-modal-close {
 width: 36px;
 height: 36px;
 border-radius: 8px;
 border: none;
 background: #f3f4f6;
 color: #6b7280;
 display: flex;
 align-items: center;
 justify-content: center;
 cursor: pointer;
 transition: all 0.2s;
 flex-shrink: 0;
}

.workforce-modal-close:hover {
 background: #e5e7eb;
 color: #374151;
}

.workforce-modal-body {
 padding: 28px;
 overflow-y: auto;
 flex: 1;
 min-height: 0;
}

.workforce-form-section {
 margin-bottom: 28px;
}

.workforce-form-section:last-child {
 margin-bottom: 0;
}

.workforce-section-title {
 font-size: 14px;
 font-weight: 600;
 color: #374151;
 margin: 0 0 16px 0;
 padding-bottom: 8px;
 border-bottom: 2px solid #e5e7eb;
 text-transform: uppercase;
 letter-spacing: 0.5px;
}

.workforce-form-grid {
 display: grid;
 grid-template-columns: repeat(2, 1fr);
 gap: 20px;
}

@media (max-width: 768px) {
 .workforce-form-grid {
  grid-template-columns: 1fr;
 }
}

.workforce-form-group {
 display: flex;
 flex-direction: column;
 gap: 8px;
}

.workforce-label {
 font-size: 13px;
 font-weight: 600;
 color: #374151;
 display: flex;
 align-items: center;
}

.workforce-input,
.workforce-textarea {
 width: 100%;
 padding: 10px 14px;
 border: 1px solid #d1d5db;
 border-radius: 8px;
 font-size: 14px;
 color: #1f2937;
 background: white;
 transition: all 0.2s;
}

.workforce-input:focus,
.workforce-textarea:focus {
 outline: none;
 border-color: #0d6efd;
 box-shadow: 0 0 0 3px rgba(13, 110, 253, 0.1);
}

.workforce-textarea {
 resize: vertical;
 min-height: 100px;
 font-family: inherit;
}

.workforce-modal-footer {
 display: flex;
 align-items: center;
 justify-content: flex-end;
 gap: 12px;
 padding: 20px 28px;
 border-top: 1px solid #e5e7eb;
 background: #f9fafb;
}

.workforce-btn {
 display: inline-flex;
 align-items: center;
 gap: 8px;
 padding: 10px 20px;
 border-radius: 8px;
 font-size: 14px;
 font-weight: 600;
 cursor: pointer;
 transition: all 0.2s;
 border: none;
}

.workforce-btn-primary {
 background: linear-gradient(135deg, #0d6efd 0%, #0a58ca 100%);
 color: white;
}

.workforce-btn-primary:hover {
 transform: translateY(-1px);
 box-shadow: 0 4px 12px rgba(13, 110, 253, 0.4);
}

.workforce-btn-light {
 background: white;
 color: #374151;
 border: 1px solid #d1d5db;
}

.workforce-btn-light:hover {
 background: #f9fafb;
 border-color: #9ca3af;
}

.workforce-btn-danger {
 background: linear-gradient(135deg, #dc3545 0%, #bb2d3b 100%);
 color: white;
}

.workforce-btn-danger:hover {
 transform: translateY(-1px);
 box-shadow: 0 4px 12px rgba(220, 53, 69, 0.4);
}

.workforce-alert {
 padding: 12px 16px;
 border-radius: 8px;
 margin-top: 16px;
}

.workforce-alert-warning {
 background: #fef3c7;
 border: 1px solid #fbbf24;
 color: #92400e;
}

.workforce-alert.hidden {
 display: none;
}

/* Scrollbar styling for modal body */
.workforce-modal-body::-webkit-scrollbar {
 width: 8px;
}

.workforce-modal-body::-webkit-scrollbar-track {
 background: #f1f5f9;
 border-radius: 4px;
}

.workforce-modal-body::-webkit-scrollbar-thumb {
 background: #cbd5e1;
 border-radius: 4px;
}

.workforce-modal-body::-webkit-scrollbar-thumb:hover {
 background: #94a3b8;
}
</style>
